01:36:53 PM:DEBUG [logger_base.py:14] mensaje a nivel debug
01:36:53 PM:INFO [logger_base.py:15] a nivel info
01:36:53 PM:WARNING [logger_base.py:16] a nivel warning
01:36:53 PM:ERROR [logger_base.py:17] nivel error
01:36:53 PM:CRITICAL [logger_base.py:18] a nivel critical
2023-05-25 13:51:57,876:DEBUG [logger_base.py:14] mensaje a nivel debug
2023-05-25 13:51:57,877:INFO [logger_base.py:15] a nivel info
2023-05-25 13:51:57,877:WARNING [logger_base.py:16] a nivel warning
2023-05-25 13:51:57,877:ERROR [logger_base.py:17] nivel error
2023-05-25 13:51:57,877:CRITICAL [logger_base.py:18] a nivel critical
01:52:14 PM:DEBUG [logger_base.py:14] mensaje a nivel debug
01:52:14 PM:INFO [logger_base.py:15] a nivel info
01:52:14 PM:WARNING [logger_base.py:16] a nivel warning
01:52:14 PM:ERROR [logger_base.py:17] nivel error
01:52:14 PM:CRITICAL [logger_base.py:18] a nivel critical
09:35:35 AM:DEBUG [Persona.py:52] 
        If Persona: 1,
        Nombre: Juan,
        Apellido:Perez,
        Email: perez@mail.com
        
09:39:22 AM:DEBUG [Persona.py:52] 
        If Persona: 1,
        Nombre: Juan,
        Apellido:Perez,
        Email: perez@mail.com
        
09:40:45 AM:DEBUG [Persona.py:52] 
        If Persona: 1,
        Nombre: Juan,
        Apellido:Perez,
        Email: perez@mail.com
        
09:40:45 AM:DEBUG [Persona.py:55] 
        If Persona: None,
        Nombre: Jose,
        Apellido:JJ,
        Email: jj@mail.com
        
09:42:51 AM:DEBUG [Persona.py:52] 
        If Persona: 1,
        Nombre: Juan,
        Apellido:Perez,
        Email: perez@mail.com
        
09:42:51 AM:DEBUG [Persona.py:55] 
        If Persona: None,
        Nombre: Jose,
        Apellido:JJ,
        Email: jj@mail.com
        
09:42:51 AM:DEBUG [Persona.py:58] 
        If Persona: 1,
        Nombre: None,
        Apellido:None,
        Email: None
        
10:00:29 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001EA9855F560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:08:18 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001FB3B21F560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:08:36 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x00000242AA2CF560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:08:36 AM:ERROR [conexion.py:42] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
10:11:15 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000002A90A7FF560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:11:15 AM:ERROR [conexion.py:42] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
10:11:34 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x0000029AFC34F560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:11:34 AM:ERROR [conexion.py:42] Ocurrio un error: type object 'Conexion' has no attribute 'conexion'
10:12:01 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x00000102A3AAF560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:12:01 AM:ERROR [conexion.py:42] Ocurrio un error: type object 'Conexion' has no attribute 'conexion'
10:12:44 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000002309352F560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:12:44 AM:ERROR [conexion.py:42] Ocurrio un error: type object 'Conexion' has no attribute 'conexion'
10:13:33 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x00000196870EF560; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:13:33 AM:DEBUG [conexion.py:39] se abrio el cursor:<cursor object at 0x0000019685823E60; closed: 0>
